import turtle
import datetime
bg = turtle.Screen()
bg.setup()

t = turtle.Turtle()
t.speed(1000)
def drawing(h,m,s):
  t.up()
  t.goto(0,0)
  t.setheading(90)
  m += s / 60
  h = (h % 12) + (m / 60)

  for _ in range (12):
    t.forward(190)
    t.pendown()
    t.forward(20)
    t.penup()
    t.goto(0,0)
    t.right(30)
  for _ in range (60):
    t.forward(210)
    t.pendown()
    t.forward(5)
    t.penup()
    t.goto(0,0)
    t.right(6)
  
  t.pensize(9)
  t.right(h*30)
  t.pendown()
  t.forward(90)

  t.right(-90)
  t.forward(12)
  t.right(120)
  t.forward(25)
  t.right(120)
  t.forward(25)
  t.right(120)
  t.forward(12)
  t.penup()
  
  t.pensize(7)
  t.goto(0,0)
  t.setheading(90)
  t.right(m*6)
  t.pendown()
  t.forward(125)
  t.right(-90)
  t.forward(12)
  t.right(120)
  t.forward(25)
  t.right(120)
  t.forward(25)
  t.right(120)
  t.forward(12)
  t.penup()
  
  t.goto(0,0)
  t.dot(17)
  
  t.pensize(5)
  t.color('red')
  t.goto(0,0)
  t.setheading(90)
  t.right(s*6)
  t.pendown()
  t.forward(150)
  t.right(-90)
  t.forward(12)
  t.right(120)
  t.forward(25)
  t.right(120)
  t.forward(25)
  t.right(120)
  t.forward(12)
  t.penup()
  t.goto(0,0)
  
  t.hideturtle()

x = datetime.datetime.now()
x=x.strftime("%X")
x=str(x)
h, m, s = x.split(':')
h = int(h)
m = int(m)
s = int(s)
print(x)
drawing(h,m,s)

#drawing(11,45,5)
